### ISSUE TITLE
main.py has a syntax error and Documentation should be updated

### ISSUE THREAD

**Issue by akhtarkamal1-ed** [q1e123/BigBlueButton-Attendance#2]
Tested this out and main.py - Line 71 is:

j = chr(ord('A') + self.settings['week'])

Needs to be changed to:

j = chr(ord('A') + int(self.settings['week']))

Else throws TypeError: unsupported operand type(s) for +: 'int' and 'str'

Documentation needs to be updated to specify that test.xlsx needs to be added and should have Column A having all student names whose attendance is to be marked. If Week 1 is specified in config, then Column B gets populated with the attendance which is 1 if that user joined a session.

Initially from the documentation above it unclear and seems like the users attendance will be pulled from BBB and list of attendees which be populated in xlsx.

Thanks though as it works well once understood.

**Comment by q1e123** [comment]
Solved
Thanks for the remark. During the testing I never got that error.
